#a=open("priya.txt","x")
b=open("priya.txt","w")
b.write("hello")
b.close()
x=open("priya.txt","w")
x.write("how are you")
x.close()
y=open("priya.txt","a")
y.write("\n hai good morning")
y.close()
a=open("priya.txt","r")
print(a.read())
a.close()
a=open("priya.txt","r")
print(a.read(5))
a.close()
a=open("priya.txt","r")
print(a.readline())
print(a.readline())
a.close()
import os
os.remove("priya.txt")