'''a=open("veni.txt","x")'''
b=open("veni.txt","w")
b.write("hello good morning")
b.close()
x=open("veni.txt","w")
x.write("i am krishnaveni")
x.close()
y=open("veni.txt","a")
y.write("\n am from perumbavoor")
y.close()
a=open("veni.txt","r")
print(a.read())
a.close()
a=open("veni.txt","r")
print(a.read(4))
a.close()
a=open("veni.txt","r")
print(a.readline())
print(a.readline())
a.close()
