import modules
import  math
print(modules.sum(2,3))
print(max(1,2,3,4,5,6))
print(min(4,5,6,7, 8,9))
print(abs(-6))
print(pow(3,4))
print(math.pi)
print(math.sqrt(25))
print(math.factorial(5))
print(math.ceil(2.34))
print(math.floor(2.34))

import datetime
x=datetime.datetime.now()
print(x)
print(x.strftime("%A"))
print(x.strftime("%a"))
print(x.strftime("%B"))
print(x.strftime("%b"))
print(x.strftime("%Y"))
print(x.strftime("%y"))
print(x.strftime("%D"))
print(x.strftime("%d"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%M"))
print(x.strftime("%S"))
print(x.strftime("%p"))
print(x.strftime("%j"))

y=datetime.datetime(2002,2,12)
print(y)
print(y.strftime("%A"))
print(y.strftime("%j"))
