x={"carrot","potato","tomato","cucumber"}
print(x)
x={"carrot","apple","orange","carrot"}
print(x)
x.add("onion")
print(x)
y={"potato","tomato","cucumber"}
print(y)
x.update(y)
print(x)
a=x.union(y)
print(a)
z={"bike","bus","car"}
print(z)
b={"train","bus","plane","ship"}
print(b)
c=z.intersection(b)
print(c)
c=z.difference(b)
print(c)
z.remove("bike")
print(z)
z.discard("bus")
print(z)
'''z.remove("scooter")
print(z)'''
z.discard("scooter")
print(z)
z.pop()
print(z)
z.clear()
print(z)
#del z
w=["bullet","benz","duster","duke"]
print(w)
w[1]="bnw"
print(w)
x=frozenset(w)
print(x)
x[2]="dio"
print(x)